name: pregel
on:
  workflow_dispatch:
  pull_request:
    branches: [ "devel", "staging/pregel-refactor" ]
    paths:
      - "arangod/**"
      - "client-tools/**"
      - "lib/**"
      - "tests/**"
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cmake
        run: |
          cmake --preset community-developer
      - name: build
        run: |
          cmake --build --preset community-developer --target arangodbtests_pregel_actor
      - name: test
        run: |
          ctest --preset community-developer -R pregel_actor
