name: pregel
on:
  workflow_dispatch:
  pull_request:
    branches: [ "devel", "staging/pregel-refactor" ]
  push:
    branches: [ "devel", "staging/pregel-refactor" ]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cmake
        run: |
          cmake --preset community-developer -DCMAKE_C_COMPILER=clang-14 -DCMAKE_CXX_COMPILER=clang++-14 -DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld
      - name: build
        run: |
          cmake --build --preset community-developer --target arangodbtests_actor
      - name: test
        run: |
          ctest --preset community-developer -R actor
